baseURL = "https://www.everywhereitsolutions.com/"
languageCode = "en-us"
title = "Everywhere IT Solutions Ltd"
description = "Journey to the cloud"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/FullLogo_Transparent_NoBuffer (2).png"
  description = "Journey to the cloud"
  facebook = ""
  twitter = "https://twitter.com/azure"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # commentoEnable = true
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  featured_image = "/images/cloudcomputing.jpg"
  recent_posts_number = 2
  show_reading_time = true
  custom_css = ["css/custom.css"]
  body_classes = "helvetica bg-near-white"
  post_content_classes = "helvetica"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2 

[services.disqus]
  shortname = 'everywhereitsolutions'